---

- name: apt-get update
  apt:
    update-cache: yes

- name: Apply updates for Debian/Ubuntu
  apt:
    upgrade:  dist
    autoremove: yes
    state: latest
  register: patched
  delay: 10
  retries: 12
  until: patched is successful

- name: Reboot after Debian/Ubuntu updates have completed
  shell: "sleep 5 && reboot"
  async: 1
  poll: 0
  when: patched is changed

- name: Wait for the reboot to complete
  wait_for_connection:
    connect_timeout: 30
    sleep: 5
    delay: 20
    timeout: 300
  when: patched is changed


