# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    boxes = [
      { :name => "OSUpdate-ubuntu2004", :box => "geerlingguy/ubuntu2004" },
      { :name => "OSUpdate-ubuntu1804", :box => "geerlingguy/ubuntu1804" }
    ]
    boxes.each do |opts|
      config.vm.define opts[:name] do |config|
        config.vm.box = opts[:box]
        if opts[:name] == boxes.last[:name]
          config.vm.provision "ansible" do |ansible|
            ansible.playbook = "test.yml"
            ansible.verbose = "v"
            ansible.limit = "all"
          end
        end
      end
    end
  end